name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install libglm-dev
    - name: configure and build
      uses: lukka/run-cmake@v2.5
      with:
        cmakeGenerator: UnixMakefiles
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/build/'
    - name: make
      run: |
        cd build
        make
        cd ..
    - name: generate bin artefact
      run: tar -czvf linux-bin.tar.gz ./bin
    - name: archive bin
      uses: actions/upload-artifact@v2
      with:
        name: linux-bin.tar.gz
        path: ./linux-bin.tar.gz
